<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="VENKAT-PC" failures="1" tests="1" name="Leave" time="0.203" errors="0" timestamp="2020-11-19T18:40:26 AST">
  <testcase classname="leave.Sigletwo" name="@AfterTest exit" time="0.001">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at leave.Sigletwo.exit(Sigletwo.java:80)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 15 stack frames]]>
    </failure>
  </testcase> <!-- @AfterTest exit -->
  <testcase classname="leave.Sigletwo" name="test" time="0.035">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at leave.Sigletwo.test(Sigletwo.java:30)
at java.base/java.util.ArrayList.forEach(Unknown Source)
at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.base/java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- test -->
</testsuite> <!-- Leave -->
